spring:
  profiles:
    active: dev
  application:
    name: yummyboot

server:
  port: 8083

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# mybatis 打印sql语句
logging:
  level:
    yummy.boot.mapper: debug

